version: '3.8'

services:

  db:
    image: mariadb
    command: --max_allowed_packet=67108864
    volumes:
      - ./db_data:/var/lib/mysql:delegated
    restart: "no"
    ports:
      - "33089:3306"
    environment:
      MARIADB_ROOT_PASSWORD: geonetric_root_pw
      MARIADB_DATABASE: geonetric_db_new
      MARIADB_USER: geonetric_user
      MARIADB_PASSWORD: geonetric_pass

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.3-php8.2-apache
    volumes:
      - ./../meanphil-tattoo/:/var/www/html:rw
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
    ports:
      - "8091:80"
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: geonetric_user
      WORDPRESS_DB_PASSWORD: geonetric_pass
      WORDPRESS_DB_NAME: geonetric_db_new

volumes:
  db_data:
  uploads.ini: